---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  DBName:   bXlhcHBEQg==
stringData:
  conjur-map: |-   
    password: data/vault/POV/Database-MySQL-database.pov.example.com-admin/password

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secrets-access
  namespace: test-app-namespace
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: [ "get", "update" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: test-app-namespace
  name: secrets-access-binding
subjects:
  - kind: ServiceAccount
    namespace: test-app-namespace
    name: test-app-sa
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: secrets-access
