
---


apiVersion: v1
kind: Service
metadata:
  name: k8ssecret-app-service
  namespace: test-app-namespace
spec:
  type: NodePort
  selector:
    app: k8ssecret-app
  ports:
    - protocol: TCP
      port: 30003
      targetPort: 8080
      nodePort: 30003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8ssecret-app
  name: k8ssecret-app
  namespace: test-app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8ssecret-app
  template:
    metadata:
      labels:
        app: k8ssecret-app
      annotations:
        conjur.org/container-mode: sidecar
        conjur.org/secrets-refresh-interval: 10s
    spec:
      serviceAccountName: test-app-sa
      containers:
        - name: k8ssecret-app
          image: quincycheng/original-simple-golang-app:v1.0
          ports:
            - containerPort: 8080
          env:
            - name: THE_SECRET
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
           
        - image: 'cyberark/secrets-provider-for-k8s:latest'
          imagePullPolicy: Always
          name: cyberark-secrets-provider-for-k8s
          volumeMounts:
          - name: conjur-status
            mountPath: /conjur/status
          - name: jwt-token
            mountPath: /var/run/secrets/tokens
          - mountPath: /run/conjur
            name: conjur-access-token
          - mountPath: /etc/conjur/ssl
            name: conjur-certs
          - mountPath: /conjur/podinfo
            name: podinfo
          env:
            - name: JWT_TOKEN_PATH
              value: /var/run/secrets/tokens/jwt
            - name: CONTAINER_MODE
              value: init
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: K8S_SECRETS
              value: db-credentials
            - name: SECRETS_DESTINATION
              value: k8s_secrets
            - name: CONJUR_APPLIANCE_URL
              value: https://apj-secrets.secretsmgr.cyberark.cloud/api
            - name: CONJUR_ACCOUNT
              value: conjur
            - name: CONJUR_AUTHN_JWT_SERVICE_ID
              value: eks-cluster
            - name: CONJUR_AUTHN_URL
              value: https://apj-secrets.secretsmgr.cyberark.cloud/api/authn-jwt/eks-cluster
            - name: CONJUR_SSL_CERTIFICATE
              valueFrom:
                configMapKeyRef:
                  key: ssl-certificate
                  name: conjur-ssl-cert

      volumes:
        - name: conjur-status
          emptyDir:
            medium: Memory
        - name: jwt-token
          projected:
            sources:
              - serviceAccountToken:
                  path: jwt
                  expirationSeconds: 6000
                  audience: https://kubernetes.default.svc
        - emptyDir:
            medium: Memory
          name: conjur-access-token
        - emptyDir:
            medium: Memory
          name: conjur-certs
        - downwardAPI:
            defaultMode: 420
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.annotations
              path: annotations
          name: podinfo
