---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-app-sa
  namespace: test-app-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secrets-access
  namespace: test-app-namespace
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: [ "get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: test-app-namespace
  name: secrets-access-binding
subjects:
  - kind: ServiceAccount
    namespace: test-app-namespace
    name: test-app-sa
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: secrets-access
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: k8s-secrets-app2
  namespace: test-app-namespace
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: test-app-sa
          containers:
          - name: k8s-secrets-provider-namespace
            image: cyberark/secrets-provider-for-k8s:latest
            imagePullPolicy: IfNotPresent
            envFrom:
              - configMapRef:
                  name: conjur-connect
            env:
              - name: MY_POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: MY_POD_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: MY_POD_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.podIP
              - name: CONJUR_AUTHN_LOGIN
                value: "host/cd/kubernetes/dev-team-1/k8s-secrets-app2"
              - name: SECRETS_DESTINATION
                value: k8s_secrets
              - name: K8S_SECRETS
                value: synched-secrets
          restartPolicy: OnFailure