---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: random-app-sa
  namespace: important-app-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secrets-access
  namespace: important-app-namespace
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: [ "get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: important-app-namespace
  name: secrets-access-binding
subjects:
  - kind: ServiceAccount
    namespace: important-app-namespace
    name: random-app-sa
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: secrets-access
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: k8s-secrets-from-conjur
  namespace: important-app-namespace
spec:
  schedule: "0 0 1 * *" # 12:00AM on the first of every month
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: random-app-sa
          containers:
          - name: k8s-secrets-provider-namespace
            image: cyberark/secrets-provider-for-k8s:latest
            imagePullPolicy: IfNotPresent

            env:
              - name: MY_POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: MY_POD_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: MY_POD_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.podIP

              - name: SECRETS_DESTINATION
                value: k8s_secrets
              - name: K8S_SECRETS
                value: regcred
              - name: LOG_LEVEL
                value: debug
              - name: JWT_TOKEN_PATH
                value: /var/run/secrets/kubernetes.io/serviceaccount/token
              - name: CONJUR_APPLIANCE_URL
                value: https://apj-secrets.secretsmgr.cyberark.cloud/api
              - name: CONJUR_ACCOUNT
                value: conjur
              - name: CONJUR_AUTHN_JWT_SERVICE_ID
                value: dev-cluster-namespace
              - name: CONJUR_AUTHN_URL
                value: https://apj-secrets.secretsmgr.cyberark.cloud/api/authn-jwt/dev-cluster-namespace
              - name: CONJUR_SSL_CERTIFICATE
                valueFrom:
                  configMapKeyRef:
                    key: ssl-certificate
                    name: conjur-ssl-cert
          
          
          restartPolicy: OnFailure

