
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-app-sa
  namespace: test-app-namespace
---
apiVersion: v1
kind: Service
metadata:
  name: original-app-service
  namespace: test-app-namespace
spec:
  type: LoadBalancer
  selector:
    app: original-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: original-app
  namespace: test-app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: original-app
  template:
    metadata:
      labels:
        app: original-app
    spec:
      serviceAccountName: test-app-sa
      containers:
      - name: original-app-container
        image: quincycheng/original-simple-golang-app:v1.0
        ports:
        - containerPort: 8080
        env:
        - name: THE_SECRET
          value: thisIsNotSecure

---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: original-app-route
  namespace: test-app-namespace
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: original-app-service
---
