---
apiVersion: v1
kind: Namespace
metadata:
  name: random-app-namespace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: important-app-sa
  namespace: random-app-namespace
---
apiVersion: v1
kind: Service
metadata:
  name: important-app-sa-service
  namespace: random-app-namespace
spec:
  type: NodePort
  selector:
    app: important-app-sa
  ports:
    - protocol: TCP
      port: 30022
      targetPort: 8080
      nodePort: 30022
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: important-app-sa
  name: important-app-sa
  namespace: random-app-namespace

spec:
  selector:
    matchLabels:
      app: important-app-sa
  replicas: 1
  template:
    metadata:
      labels:
        app: important-app-sa
    spec:
      serviceAccountName: important-app-sa
      containers:
        - name: test-app
          image: quincycheng/api-simple-golang-app:v1.0
          ports:
            - containerPort: 8080
          volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token
            readOnly: true
          env:
            - name: CONJUR_APPLIANCE_URL
              value: https://apj-secrets.secretsmgr.cyberark.cloud/api
            - name: CONJUR_ACCOUNT
              value: conjur
            - name: CONJUR_AUTHN_JWT_SERVICE_ID
              value: dev-cluster-sa
            - name: CONJUR_AUTHN_URL
              value: https://apj-secrets.secretsmgr.cyberark.cloud/api/authn-jwt/dev-cluster-sa
            - name: CONJUR_SSL_CERTIFICATE
              valueFrom:
                configMapKeyRef:
                  key: ssl-certificate
                  name: conjur-ssl-cert

        - image: cyberark/conjur-authn-k8s-client
          imagePullPolicy: Always
          name: authenticator
          env:
            - name: JWT_TOKEN_PATH
              value: /var/run/secrets/kubernetes.io/serviceaccount/token
            - name: CONJUR_APPLIANCE_URL
              value: https://apj-secrets.secretsmgr.cyberark.cloud/api
            - name: CONJUR_ACCOUNT
              value: conjur
            - name: CONJUR_AUTHN_JWT_SERVICE_ID
              value: dev-cluster-sa
            - name: CONJUR_AUTHN_URL
              value: https://apj-secrets.secretsmgr.cyberark.cloud/api/authn-jwt/dev-cluster-sa
            - name: CONJUR_SSL_CERTIFICATE
              valueFrom:
                configMapKeyRef:
                  key: ssl-certificate
                  name: conjur-ssl-cert


          volumeMounts:
            - mountPath: /run/conjur
              name: conjur-access-token
            - mountPath: /var/run/secrets/tokens
              name: jwt-token
      volumes:
        - name: conjur-access-token
          emptyDir:
            medium: Memory
        - name: jwt-token
          projected:
            sources:
              - serviceAccountToken:
                  path: jwt
                  expirationSeconds: 6000
                  audience: conjur
