---
apiVersion: v1
kind: Namespace
metadata:
  name: test-app-namespace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-app-sa
  namespace: test-app-namespace
---
apiVersion: v1
kind: Service
metadata:
  name: original-app-service
  namespace: test-app-namespace
spec:
  type: NodePort
  selector:
    app: original-app
  ports:
    - protocol: TCP
      port: 30001
      targetPort: 8080
      nodePort: 30001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: original-app
  namespace: test-app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: original-app
  template:
    metadata:
      labels:
        app: original-app
    spec:
      serviceAccountName: test-app-sa
      containers:
      - name: original-app-container
        image: quincycheng/original-simple-golang-app:v1.0
        ports:
        - containerPort: 8080
        env:
        - name: THE_SECRET
          value: thisIsNotSecure
